version: "2.3"

services:
  camerarelay:
    # build: .
    image: aletheiaai/deployments:camerarelay.main
    # network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    restart: always  # autorestart on fail or config change from WebUI
    environment:
      - TZ=Asia/Karachi  # timezone in logs
    volumes:
      - "./config:/config"   # folder for go2rtc.yaml file (edit from WebUI)
      - "./videos:/videos"
    ports:
      - 1984:1984
      - 8554:8554