api:
    origin: '*'
    # username: "admin@aletheia-ai.tech"
    # password: "Aletheia@123"
rtsp:
    default_query: video
    listen: :8554
    password: abc12345
    username: admin
streams:
    cam001: null
    cam001_output: null
    cam002: null
    cam002_output: null

