mongodb_connection_string: "mongodb://172.17.0.1:27017"

camera_id: ['cam501','cam502','cam503','cam504']

heatmap_fps: 25
heatmap_time_segments: [1, 23]

heatmap_frame_width: 1920
heatmap_frame_height: 1080

dwell_time_threshold: 500
occupancy_send: False
occupancy_send_api: 'http://172.17.0.1:8000/api/systemcount/personOccupancy'

counting_zones:
  'cam501':
    Table1: [[201, 610], [764, 495], [1342, 918], [1067, 1078], [288, 1077]]
    Table2: [[192, 392], [567, 331], [760, 489], [201, 602]]
  'cam502':
    Table1: [[195, 1069], [292, 562], [946, 517], [1123, 1075]]
    Table2: [[294, 558], [426, 290], [837, 283], [937, 522]]
    Table3: [[1913, 1010], [1428, 469], [1476, 346], [1751, 351], [1917, 496]]
  'cam503':
    Table1: [[4, 740], [-2, 645], [201, 482], [379, 519], [138, 803]]
    Table2: [[363, 424], [552, 283], [747, 299], [575, 487]]
    Table3: [[788, 465], [919, 297], [1164, 307], [1104, 480]]
    Table4: [[400, 889], [673, 515], [1036, 563], [859, 1036]]
  'cam504':
    Table1: [[2, 792], [119, 664], [708, 673], [690, 1075], [11, 1075]]
    Table2: [[132, 656], [411, 377], [807, 357], [692, 682]]
    Table3: [[1010, 255], [1374, 227], [1538, 342], [1064, 389]]
    Table4: [[1084, 422], [1549, 357], [1837, 614], [1151, 744]]

heatmap_masking_coordinates:
  'cam501': [[311, 1071], [199, 586], [180, 288], [513, 257], [1558, 1077]]
  'cam502': [[186, 1065], [292, 569], [489, 199], [1359, 160], [1915, 470], [1915, 1071]]
  'cam503': [[2, 645], [589, 268], [1716, 320], [1915, 548], [1911, 1075], [9, 1075]]
  'cam504': [[2, 814], [485, 258], [1389, 214], [1910, 656], [1906, 1071], [6, 1065]]
  
 
heatmap_detection_area:
  'cam501': True          #     True or False
  'cam502': True
  'cam503': True
  'cam504': True

camera_type:
  'cam501': normal  # fisheye or normal       #     True or False
  'cam502': normal  # fisheye or normal
  'cam503': normal  # fisheye or normal
  'cam504': normal  # fisheye or normal
  # 'cam505': fisheye # fisheye or normal

draw_region_boxes: True
show_zone_counts: True

############################################ END OF HEATMAPS ################################################

debug_log: 0
heatmaps_server_address: 0.0.0.0:5454
classes_detection_names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
  'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking
    meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
  'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
  'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
  'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
  'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog',
  'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table',
  'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
  'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
  'teddy bear', 'hair drier', 'toothbrush']
classes_tracked_ids:
- 0
# - 1
LICENSE_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb21wYW55IjoiQWxldGhlaWEtQUkiLCJlbWFpbCI6InNhZGFtLmh1c3NhaW5AYWxldGhlaWEtYWkudGVjaCIsImlhdCI6MTcyODYzMDExMiwibmJmIjoxNzI4NTA3NjAwLCJleHAiOjE5MTc4MTAwMDB9.AbHQ_WabRNXzuDPO_GxNx1KNlvZYmJG5JB296vJarZCMy3eGh3UsM9YVGRJshDn6YB2FA7cxLDdg-n3iv8bBgyfWOzru-qUNYXZOj7CR1YvKNbTXTlXZ8qlHOSgWmLNcQkFcGUM7Y4Ld5Tk0RieQLMWWAS5ufgDGQRlg4ZBFYFkr0aIrlsoP95UhuWPR1910zPyCPXQpFUrKHo1DkylR36sR-chl6W1mEICyf34aHWOBASbIcAr7h9FlqUqzMXw0-PIOH1kyq6Ch4XnWdyhEME79ABow7gQoNcT-qQA-pigG59TBFexeyr2u-7foJxamNBjzVR5dgRvaRTvo73gmUg
cam_id: cam501